### ISSUE TITLE
[CLM/Azure DevOps Extension] AssemblyInfo support

### ISSUE THREAD

**Issue by AleksandarDev** [Enterwell/ChangelogManager#78]
When using with old .NET projects, we manually determine versions, bump it in our files and then call CLM with already changed version just to merge changelog file like so:

```yaml
    - template: azure-pipeline-bump-version-template.yml@DevOps
      parameters:
        repoPath: $(checkoutPath)
        changesPath: "$(checkoutPath)/changes"
        assemblyInfoLocationFilter: "$(checkoutPath)/Project/Properties"
    
    - task: MergeChangelog@1
      condition: eq(variables['Build.SourceBranchName'], 'main')
      inputs:
        semanticVersion: $(bumpedVersionNoRevisionString)
        changelogLocation: $(checkoutPath)
```

It would be nice to remove the first step and just use:

```yaml
    - task: MergeChangelog@3
      inputs:
            changelogLocation: $(checkoutPath)
            shouldMergeChangelog: eq(variables['Build.SourceBranchName'], 'main')
            shouldBumpVersion: true
            pathToProjectFile: "$(checkoutPath)/Project/Properties/AssemblyInfo.cs"
            revision: $(Build.BuildId)
```

or

```yaml
    - task: MergeChangelog@3
      displayName: "Bump version"
      inputs:
            changelogLocation: $(checkoutPath)
            shouldMergeChangelog: false
            shouldBumpVersion: true
            pathToProjectFile: "$(checkoutPath)/Project/Properties/AssemblyInfo.cs"
            revision: $(Build.BuildId)

    - task: MergeChangelog@3
      displayName: "Merge changelog"
      condition: eq(variables['Build.SourceBranchName'], 'main')
      inputs:
            changelogLocation: $(checkoutPath)
```

Assembly info has following line to define version:

```csharp
[assembly: AssemblyVersion("2.4.58.43218")]
```

With following format: <Major>.<Minor>.<Patch>.<Revision>.

To support this scenario we could do following:

- [ ] new flag `shouldMergeChangelog` to disable changelog merging for staging builds (only version is bumped for build and publish, not actually pushed to staging branch, on main branch we merge changelog)
- [ ] `pathToProjectFile` to support `AssemblyVersion` versioning
- [ ] new flag `revisionNumber` to add support for 4 numbers long versions when provided - write-only (this is not bumped automatically, just persisted if there and replaced if provided)
